controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
# SECURITY
app_login:
    path: /login
    controller: App\Controller\SecurityController::login
app_logout:
    path: /logout
    controller: App\Controller\SecurityController::logout
# REGISTER
app_register:
    path: /register
    controller: App\Controller\RegistrationController::register
# FRIENDS
app_friends_list:
    path: /friends
    controller: App\Controller\FriendsController::list
app_friend_add:
    path: /friend/add
    controller: App\Controller\FriendsController::add
app_friend_remove:
    path: /friend/remove/{id}
    controller: App\Controller\FriendsController::remove
app_friend_accept:
    path: /friend/accept/{id}
    controller: App\Controller\FriendsController::accept
# PAYMENTS
app_payments:
    path: /payments
    controller: App\Controller\PaymentsController::index
# NOTIFIACTION
app_notification_list:
    path: /notifications
    controller: App\Controller\NotificationsController::list
