controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
# HOMEPAGE
app_homepage:
    path: /
    controller: App\Controller\HomepageController::index
# SECURITY
app_login:
    path: /login
    controller: App\Controller\SecurityController::login
app_logout:
    path: /logout
    controller: App\Controller\SecurityController::logout
# REGISTER
app_register:
    path: /register
    controller: App\Controller\RegistrationController::register
# FRIENDS
app_friends_list:
    path: /friends
    controller: App\Controller\FriendsController::list
app_friend_add:
    path: /friend/add
    controller: App\Controller\FriendsController::add
app_friend_remove:
    path: /friend/remove/{id}
    controller: App\Controller\FriendsController::remove
app_friend_accept:
    path: /friend/accept/{idUser}/{id}
    controller: App\Controller\FriendsController::accept
app_friend_decline:
    path: /friend/decline/{idUser}/{id}
    controller: App\Controller\FriendsController::decline
# PAYMENTS
app_payments_made_list:
    path: /payments/made/list
    controller: App\Controller\PaymentsController::madePaymentsList
app_payments_clearing_list:
    path: /payments/clearing/list
    controller: App\Controller\PaymentsController::clearingPaymentsList
app_payments_set_clearing:
    path: /payment/cleared/{id}
    controller: App\Controller\PaymentsController::setClearing
app_payments_add:
    path: /payment/add
    controller: App\Controller\PaymentsController::add
app_billings:
    path: /billings
    controller: App\Controller\PaymentsController::billings
# NOTIFIACTION
app_notification_list:
    path: /notifications
    controller: App\Controller\NotificationsController::list
# API
api_get_notifications:
    path: /api/notifications/get
    methods: GET
    controller: App\Controller\NotificationsController::getNotifications
api_get_user_data:
    path: /api/user/get
    methods: GET
    controller: App\Controller\Api\UserApiController::getActiveUserData
